export const DATABASE_DEFAULTS = {
  HOST: 'localhost',
  PORT: 5432,
  POOL_MAX: 10,
  POOL_MIN: 2,
  ACQUIRE_TIMEOUT_MS: 5_000,
  STATEMENT_TIMEOUT_MS: 5_000,
  IDLE_IN_TRANSACTION_TIMEOUT_MS: 10_000,
  MAX_LIFETIME_SECONDS: 1_800,
  APPLICATION_NAME: 'core-api',
  EMPTY: '',
  SSL_ENABLED: 'true'
} as const;
