export const ADDRESS = {
  PATH: '/users/me/address',
  SEARCH_PATH: '/search',
  REVERSE_PATH: '/reverse',
  QUERY_PARAM: 'q',
  LATITUDE_PARAM: 'latitude',
  LONGITUDE_PARAM: 'longitude',
  DEBOUNCE_MS: 400,
  MIN_QUERY: 3,
  SOURCES: { MANUAL: 'MANUAL', MAP: 'MAP', CURRENT_LOCATION: 'CURRENT_LOCATION' },
  STYLESHEET_HREF: 'leaflet.css',
  STYLESHEET_ID: 'leaflet-stylesheet',
  STYLESHEET_REL: 'stylesheet',
  LINK_TAG: 'link',
  TILE_URL: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png',
  ATTRIBUTION: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
  DEFAULT_CENTER: [51.505, -0.09],
  DEFAULT_ZOOM: 3,
  PICKED_ZOOM: 16,
  MAX_ZOOM: 19,
  GEO_TIMEOUT_MS: 10_000,
  GEO_MAX_AGE_MS: 60_000,
  BLANK_LABEL: '',
  CLICK_EVENT: 'click',
  DRAG_END_EVENT: 'dragend',
  LINE_MAX: 200,
  CITY_MAX: 120,
  POSTAL_MAX: 20,
  PIN_CLASS: 'address-pin',
  PIN_HTML: '<span class="block h-7 w-7 rounded-full border-4 border-white bg-primary shadow-lg"></span>',
  PIN_SIZE: 28,
  PERMISSION_DENIED: 1,
  POSITION_UNAVAILABLE: 2,
  TIMEOUT: 3
} as const;
