export const GAME_EVENT_AUDIT = {
  ENTITY_TYPE: 'GameEvent',
  CREATED: 'GAME_EVENT_CREATED',
  STATUS_CHANGED: 'GAME_EVENT_STATUS_CHANGED',
  RESULT_RECORDED: 'GAME_EVENT_RESULT_RECORDED'
} as const;
