export const PASSKEY = {
  CHALLENGE_PREFIX: 'passkey-challenge:',
  CHALLENGE_TTL_SECONDS: 300,
  RP_NAME_KEY: 'PASSKEY_RP_NAME',
  RP_ID_KEY: 'PASSKEY_RP_ID',
  ORIGIN_KEY: 'PASSKEY_ORIGIN',
  NO_ORIGIN: '',
  DEFAULT_RP_NAME: 'Wallet',
  ATTESTATION: 'none',
  USER_VERIFICATION: 'preferred',
  RESIDENT_KEY: 'required',
  REGISTER_SCOPE: 'register',
  LOGIN_SCOPE: 'login',
  STEP_UP_SCOPE: 'step-up',
  GRANT_PREFIX: 'passkey-step-up:',
  GRANT_TTL_SECONDS: 300,
  GRANT_VALUE: 'granted',
  STEP_UP_ENABLED_KEY: 'PASSKEY_STEP_UP_ENABLED',
  STEP_UP_ENABLED_VALUE: 'true',
  PASSKEY_REQUIRED_MESSAGE: 'Add a passkey on your profile before locking a chat',
  STEP_UP_REQUIRED_MESSAGE: 'Confirm with your passkey before continuing',
  STEP_UP_CONFIRMED_MESSAGE: 'Confirmed. Continue within the next five minutes.',
  NO_CHALLENGE_MESSAGE: 'Start the passkey ceremony again; the challenge has expired',
  NOT_VERIFIED_MESSAGE: 'That passkey could not be verified',
  UNKNOWN_CREDENTIAL_MESSAGE: 'That passkey is not registered',
  CLONED_MESSAGE: 'This passkey looks cloned and was refused',
  NOT_FOUND_MESSAGE: 'Passkey not found',
  REMOVED_MESSAGE: 'Passkey removed'
} as const;
