export const MONEY_AUDIT = {
  ACTOR_SERVICE: 'core-api',
  WALLET: 'Wallet',
  PAYMENT: 'Payment',
  WALLET_CREDITED: 'WALLET_CREDITED',
  WALLET_DEBITED: 'WALLET_DEBITED',
  PAYMENT_COMPLETED: 'PAYMENT_COMPLETED',
  PAYMENT_FAILED: 'PAYMENT_FAILED'
} as const;
