import { HTTP_STATUS } from './http-status.constant';

export const BET_SETTLEMENT_TEST = {
  ...HTTP_STATUS,
  EMAIL: 'player17@realtime-wallet-payments.com',
  ADMIN_EMAIL: 'admin@realtime-wallet-payments.com',
  MAX_BETS: 20,
  STAKE_MINOR: 100,
  SELECTION: 'Home',
  WON: 'WON',
  LOST: 'LOST',
  PENDING: 'PENDING',
  BETS_PATH: '/bets',
  SETTLEMENT_SUFFIX: '/settlement',
  SETTLEMENT_KEY: 'settlement-',
  ADMIN_PAYOUT_KEY: 'settlement-admin-payout-',
  DRAW_AUDIT_KEY: 'settlement-draw-audit',
  OVERPAY_FACTOR: 1000,
  TIMEOUT_MS: 60_000,
  NOTIFY_WAIT_MS: 20_000,
  NOTIFY_POLL_MS: 500,
  DEFAULT_DIGITS: 2,
  BASE: 10,
  LOCALE: 'en',
  CURRENCY_STYLE: 'currency',
  NO_LOSING_BET: 'No losing bet to re-settle',
  WALLET_SQL: 'SELECT w.id, w.currency FROM wallets w JOIN users u ON u.id = w.user_id WHERE u.email = $1',
  EVENT_SQL: "SELECT id FROM game_events WHERE status = 'SCHEDULED' AND betting_closes_at > now() ORDER BY starts_at LIMIT 1",
  SETTLED_EVENTS_SQL: "SELECT count(*)::int AS count FROM outbox_events WHERE aggregate_id = ANY($1) AND event_type = 'bet.settled'",
  WIN_NOTIFICATIONS_SQL: "SELECT n.content FROM notifications n JOIN users u ON u.id = n.user_id WHERE u.email = $1 AND n.type = 'BET_WON'",
  REOPEN_SQL: `UPDATE bets SET status = 'PENDING', payout_minor = NULL, settled_at = NULL, settlement_ledger_transaction_id = NULL,
               draw_value = NULL, draw_threshold = NULL WHERE id = $1`,
  PAYOUT_SQL: 'SELECT status, payout_minor FROM bets WHERE id = $1',
  DRAW_SQL: 'SELECT draw_value, draw_threshold FROM bets WHERE id = $1',
  DRAW_AUDIT_SQL: 'SELECT status, draw_value, draw_threshold, odds_at_placement FROM bets WHERE id = $1'
} as const;
