export const INTEGRATION_STACK = {
  MINIO_PORT: 9000,
  MINIO_USER: 'integration',
  MINIO_PASSWORD: 'integration-secret',
  MINIO_COMMAND: ['server', '/data'],
  MINIO_HEALTH_PATH: '/minio/health/live',
  JWT_ISSUER: 'core-api-integration',
  READY_TIMEOUT_MS: 90_000,
  READY_POLL_MS: 500,
  READY_PATH: '/game-events',
  STOP_GRACE_MS: 15_000,
  APP_DB_USERNAME: 'app_api',
  APP_WORKER_USERNAME: 'app_worker',
  RABBITMQ_HTTP_PORT: 15_672,
  DATABASE_NAME: 'core_api_test',
  LOOPBACK: '127.0.0.1',
  REDIS_PASSWORD_BYTES: 12,
  DB_PASSWORD_BYTES: 16,
  KEY_BYTES: 32,
  KEY_ENCODING: 'base64',
  WORK_DIR_PREFIX: 'core-api-integration-',
  MIGRATE_BIN: 'node_modules/.bin/node-pg-migrate',
  MIGRATIONS_DIR: 'migrations',
  PROVISION_SCRIPT: 'scripts/db/provision-login-roles.mjs',
  API_ENTRY: 'dist/main.js',
  API_PREFIX: '/api/v1',
  KAFKA_READY_LOG: /Kafka Server started/,
  KAFKA_CONTROLLER_PORT: 9093,
  STATIC_ENV: {
    NODE_ENV: 'development',
    EMAIL_FROM: 'no-reply@core-api.test',
    JWT_EXPIRES_IN: '15m',
    RABBITMQ_DEFAULT_USER: 'guest',
    RABBITMQ_DEFAULT_PASS: 'guest',
    KAFKA_CONSUMER_GROUP_ID: 'core-api-integration',
    STORAGE_STRATEGY: 's3',
    STORAGE_BUCKET_NAME: 'integration',
    STORAGE_REGION: 'us-east-1',
    STORAGE_FORCE_PATH_STYLE: 'true',
    STORAGE_ENSURE_BUCKET: 'true',
    PAYMENT_SIMULATION: 'true',
    WEBHOOK_REPLAY_INTERVAL_MS: '500',
    WEBHOOK_REPLAY_STALE_AFTER_MS: '5000',
    PAYMENT_RECONCILE_INTERVAL_MS: '500',
    TASK_POLL_MS: '200',
    PAYMENT_RECONCILE_STALE_AFTER_MS: '30000',
    TRUST_PROXY: '1',
    MFA_ISSUER: 'Integration Wallet',
    REFRESH_GRACE_MS: '800',
    PASSKEY_RP_NAME: 'Integration Wallet',
    PASSKEY_STEP_UP_ENABLED: 'true'
  }
} as const;
