export const LOGIN_STATUS_TEST = {
  ACTIVE_EMAIL: 'player3@realtime-wallet-payments.com',
  SUSPENDED_EMAIL: 'player4@realtime-wallet-payments.com',
  CLOSED_EMAIL: 'player5@realtime-wallet-payments.com',
  PENDING_EMAIL: 'player6@realtime-wallet-payments.com',
  GLOBAL_ADMIN_EMAIL: 'global_admin@realtime-wallet-payments.com',
  STAFF_EMAIL: 'admin@realtime-wallet-payments.com',
  TERMS_EMAIL: 'terms@integration.test',
  LIFECYCLE_EMAIL: 'lifecycle@integration.test',
  INVITED_EMAIL: 'invited@integration.test',
  ADMIN_VERIFIED_EMAIL: 'admin-verified@integration.test',
  UNKNOWN_EMAIL: 'ghost@integration.test',
  WARM_UP_EMAIL: 'warm-up@integration.test',
  WRONG_PASSWORD: 'Wrong#Pass2026',
  TERMS_PASSWORD: 'Terms#Pass2026',
  LIFECYCLE_PASSWORD: 'Lifecycle#Pass2026',
  INVITED_PASSWORD: 'Invited#Pass2026',
  ADMIN_VERIFIED_PASSWORD: 'AdminVerified#2026',
  INVALID_CREDENTIALS: 'Invalid credentials',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  CLOSED: 'CLOSED',
  PENDING: 'PENDING',
  MODERATOR: 'MODERATOR',
  LOGIN_PATH: '/auth/login',
  REGISTER_PATH: '/auth/register',
  VERIFY_PATH: '/auth/verify-email',
  SET_PASSWORD_PATH: '/auth/set-password',
  USERS_PATH: '/users',
  EMAIL_VERIFICATION_SUFFIX: '/email-verification',
  WALLETS_PATH: '/wallets',
  TOKEN_PARAM: 'token',
  ACCESS_TOKEN: 'accessToken',
  SESSION_PREFIX: 'session:',
  KEEP_TTL: 'KEEPTTL',
  TIMING_RUNS: 10,
  MEDIAN_INDEX: 5,
  MIN_TIMING_RATIO: 0.5,
  MAX_TIMING_RATIO: 2,
  SEED_STATUS_SQL: `UPDATE users SET status = v.status
                      FROM (VALUES ('player4@realtime-wallet-payments.com', 'SUSPENDED'), ('player5@realtime-wallet-payments.com', 'CLOSED'),
                                   ('player6@realtime-wallet-payments.com', 'PENDING')) v(email, status)
                     WHERE users.email = v.email`,
  COUNT_SQL: 'SELECT count(*)::int AS count FROM users WHERE email = $1',
  TERMS_SQL: "SELECT terms_accepted_at > now() - interval '1 minute' AS accepted_recently FROM users WHERE email = $1",
  STATUS_BY_EMAIL_SQL: 'SELECT status FROM users WHERE email = $1',
  STATUS_BY_ID_SQL: 'SELECT status FROM users WHERE id = $1',
  ID_BY_EMAIL_SQL: 'SELECT id FROM users WHERE email = $1',
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401
} as const;
