export const MFA_TEST = {
  SETUP_EMAIL: 'mfa-setup-player@support-tests.realtime-wallet-payments.com',
  LOGIN_EMAIL: 'mfa-login-player@support-tests.realtime-wallet-payments.com',
  STATUS_PATH: '/auth/mfa/status',
  SETUP_PATH: '/auth/mfa/setup',
  ENABLE_PATH: '/auth/mfa/enable',
  DISABLE_PATH: '/auth/mfa/disable',
  VERIFY_PATH: '/auth/mfa/verify',
  LOGIN_PATH: '/auth/login',
  WALLETS_PATH: '/wallets',
  SECRET_PARAM: 'secret',
  WRONG_CODE: '000000',
  WRONG_PASSWORD: 'Wrong#Pass2026',
  RECOVERY_CODE_COUNT: 10,
  MAX_FAILED_ATTEMPTS: 5,
  WINDOW_SECONDS: 30,
  MS_PER_SECOND: 1000,
  OTPAUTH_PATTERN: /^otpauth:\/\/totp\/.*issuer=Integration%20Wallet/,
  QR_PATTERN: /^data:image\/png;base64,/,
  PLAIN_SECRET_SQL: "SELECT position(convert_to($2, 'UTF8') IN mfa_secret_encrypted) AS plain_at FROM users WHERE email = $1",
  CLEARED_SQL: `SELECT u.mfa_secret_encrypted IS NULL AS secret_cleared, count(c.id) FILTER (WHERE c.used_at IS NULL)::int AS unused_codes
                  FROM users u LEFT JOIN mfa_recovery_codes c ON c.user_id = u.id WHERE u.email = $1 GROUP BY u.id`,
  TOKEN_ROW_SQL: 'SELECT failed_attempts, revoked_at IS NOT NULL AS revoked, used_at IS NOT NULL AS used FROM auth_tokens WHERE token_hash = $1',
  RECENT_LOGIN_SQL: "SELECT last_login_at > now() - interval '1 minute' AS recent FROM users WHERE email = $1",
  EXPIRE_SQL: "UPDATE auth_tokens SET created_at = now() - interval '10 minutes', expires_at = now() - interval '5 minutes' WHERE token_hash = $1",
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  CONFLICT: 409
} as const;
