export const SESSION_POLICY = {
  ACCESS_TTL_SECONDS: 900,
  REFRESH_USER: 'player3@realtime-wallet-payments.com',
  REPLAY_USER: 'player2@realtime-wallet-payments.com',
  LOGOUT_ALL_USER: 'player1@realtime-wallet-payments.com',
  WALLETS_PATH: '/wallets',
  ME_PATH: '/users/me',
  LOGIN_PATH: '/auth/login',
  REFRESH_PATH: '/auth/refresh',
  LOGOUT_PATH: '/auth/logout',
  LOGOUT_ALL_PATH: '/auth/logout-all',
  OK: 200,
  GRACE_WAIT_MS: 1200,
  CREATED: 201,
  UNAUTHORIZED: 401,
  TOKEN_FIELD: 'refreshToken',
  TOKEN_COOKIE: 'refresh_token',
  HTTP_ONLY: 'HttpOnly',
  SAME_SITE: 'SameSite=Lax',
  TICKET_PATH: '/notifications/stream-ticket',
  STREAM_PATH: '/notifications/stream',
  TICKET_QUERY: '?ticket=',
  TOKEN_QUERY: '?token=',
  ACCESS_TOKEN_FIELD: 'accessToken',
  USER_FIELD: 'user'
} as const;
