export const TEST_ENV_KEYS = {
  API_URL: 'CORE_API_TEST_URL',
  APP_DATABASE_URL: 'CORE_API_TEST_APP_DATABASE_URL',
  DATABASE_URL: 'CORE_API_TEST_DATABASE_URL',
  KAFKA_BROKERS: 'CORE_API_TEST_KAFKA_BROKERS',
  RABBITMQ_MANAGEMENT_URL: 'CORE_API_TEST_RABBITMQ_MANAGEMENT_URL',
  RABBITMQ_URL: 'CORE_API_TEST_RABBITMQ_URL',
  REDIS_URL: 'CORE_API_TEST_REDIS_URL'
} as const;
