export const LIMITER_TEST = {
  LABEL: 'stripe',
  FAST_MS: 200,
  SHORT_DEADLINE_MS: 20,
  SLOW_MS: 60,
  MAX_CONCURRENT: 2,
  QUEUE_LIMIT: 1,
  RESULT: 'ok',
  DEADLINE_CATEGORY: 'NETWORK',
  BULKHEAD_CATEGORY: 'CIRCUIT_OPEN'
} as const;
