export const GEOCODER = {
  BASE_URL_KEY: 'GEOCODER_BASE_URL',
  DEFAULT_BASE_URL: 'https://nominatim.openstreetmap.org',
  SEARCH_PATH: '/search',
  REVERSE_PATH: '/reverse',
  FORMAT_PARAM: 'format',
  FORMAT: 'jsonv2',
  DETAILS_PARAM: 'addressdetails',
  DETAILS: '1',
  LIMIT_PARAM: 'limit',
  LIMIT: '5',
  QUERY_PARAM: 'q',
  LAT_PARAM: 'lat',
  LON_PARAM: 'lon',
  HEADERS: { 'user-agent': 'RealtimeWalletAddress/1.0', accept: 'application/json' },
  TIMEOUT_MS: 5_000,
  RATE_KEY: 'geocode:provider',
  RATE_WINDOW_MS: 1_000,
  RATE_LIMIT: 1,
  SEARCH_CACHE: 'geocode:search',
  REVERSE_CACHE: 'geocode:reverse',
  CACHE_TTL_SECONDS: 82800,
  QUERY_MIN: 3,
  QUERY_MAX: 200,
  UNAVAILABLE_MESSAGE: 'Address lookup is busy right now. Type your address or try again in a moment.'
} as const;
