export const MONITORING = {
  CONTROLLER_PATH: 'monitoring',
  ALERTS_PATH: 'alerts',
  TOKEN_KEY: 'ALERT_WEBHOOK_TOKEN',
  AUTHORIZATION_HEADER: 'authorization',
  BEARER_PREFIX: 'Bearer ',
  DIGEST: 'sha256',
  UNAUTHORIZED_MESSAGE: 'Invalid alert webhook token',
  USERS_TABLE: 'users',
  ADMINS_SQL: `SELECT id, email FROM users
                WHERE role IN ('GLOBAL_ADMIN', 'ADMIN') AND status = 'ACTIVE' AND deleted_at IS NULL`,
  FIRING: 'firing',
  ALERTNAME_LABEL: 'alertname',
  SEVERITY_LABEL: 'severity',
  SUMMARY_ANNOTATION: 'summary',
  DESCRIPTION_ANNOTATION: 'description',
  RECOVERY_ANNOTATION: 'recovery',
  RESOLVED_PREFIX: 'Resolved: ',
  TITLE_SEPARATOR: ' · ',
  UNKNOWN: 'unknown',
  LASTED_PREFIX: 'It lasted ',
  BACK_TO_NORMAL: 'Back to normal.',
  SENTENCE_END: '.',
  MINUTE_MS: 60_000,
  MINUTES_PER_HOUR: 60,
  MINUTES_UNIT: ' min',
  HOURS_UNIT: ' h',
  UNIT_GAP: ' ',
  AGGREGATE_TYPE: 'User',
  EMAIL_PURPOSE: 'monitoring-alert',
  ADMIN_PATH: '/admin'
} as const;
