export const SECRETS_CONSTANTS = {
  ENV_FILE_ENCODING: 'utf8',
  DEFAULT_REGION: 'us-east-1',
  LOGGER_CONTEXT: 'SecretsLoader',
  KEYS: {
    SOURCE: 'SECRETS_SOURCE',
    ID: 'SECRETS_ID',
    REGION: 'SECRETS_REGION',
    ENDPOINT: 'SECRETS_ENDPOINT',
    ACCESS_KEY_ID: 'SECRETS_ACCESS_KEY_ID',
    SECRET_ACCESS_KEY: 'SECRETS_SECRET_ACCESS_KEY'
  },
  ERRORS: {
    MISSING_ID: 'SECRETS_SOURCE is aws but SECRETS_ID is not set',
    EMPTY_SECRET: 'Secret has no string value'
  }
} as const;
