export const RABBITMQ_TOPOLOGY = {
  PREFETCH: 10,
  RETRY_DELAYS_MS: [5_000, 30_000, 300_000],
  RETRY_SUFFIX: 'retry',
  DLQ_SUFFIX: 'dlq',
  ATTEMPTS_HEADER: 'x-attempts',
  ERROR_HEADER: 'x-last-error',
  QUEUE_HEADER: 'x-origin-queue',
  ERROR_MAX_LENGTH: 500,
  RECONNECT_BASE_MS: 1_000,
  RECONNECT_MAX_MS: 30_000,
  DRAIN_TIMEOUT_MS: 5_000,
  DRAIN_POLL_MS: 50,
  REPLAY_DEFAULT_LIMIT: 100
} as const;
