export const NOTIFICATION_TYPES = ['BET_WON', 'INFO', 'PAYMENT_COMPLETED', 'PAYMENT_FAILED', 'SYSTEM', 'WALLET_CREDITED', 'WALLET_DEBITED'] as const;

export const NOTIFICATION_STATUSES = ['FAILED', 'PENDING', 'READ', 'SENT'] as const;
