export const POOL_CONSTANTS = {
  DEFAULT_MAX: 10,
  DEFAULT_MIN: 2,
  DEFAULT_IDLE_TIMEOUT_MS: 30_000,
  DEFAULT_CONNECTION_TIMEOUT_MS: 2_000,
  DEFAULT_STATEMENT_TIMEOUT_MS: 5_000,
  DEFAULT_IDLE_IN_TRANSACTION_TIMEOUT_MS: 10_000,
  DEFAULT_MAX_LIFETIME_SECONDS: 1_800,
  DISCONNECT_TIMEOUT_MS: 2_000,
  RETRY_BACKOFF_BASE_MS: 100,
  ACTOR_SETTING: 'app.current_user_id',
  SET_ACTOR_SQL: 'SELECT set_config($1, $2, true)'
} as const;
