export const INFO_DIALOG = {
  PAGES: { MAIN: 'main', SHARED: 'shared', STARRED: 'starred', STORAGE: 'storage', PRIVACY: 'privacy', LOCK: 'lock', DETAILS: 'details', MUTE: 'mute', THEME: 'theme', CLEAR: 'clear' },
  TITLE_ID: 'info-dialog-title',
  TITLE_REVEAL_PX: 170,
  CARD: 'block overflow-hidden rounded-[10px] bg-chat-card shadow-[0_1px_0_rgba(0,0,0,0.04)] dark:bg-chat-card-dark [&>app-info-row+app-info-row_.row-line]:border-t',
  CLOSE_LABEL: 'Close contact info',
  BACK_LABEL: 'Back',
  VOICE: 'Voice',
  VIDEO: 'Video',
  SEARCH: 'Search',
  SHARED_ROW: 'Media, links and docs',
  STARRED_ROW: 'Starred',
  STORAGE_ROW: 'Manage storage',
  PRIVACY_ROW: 'Advanced chat privacy',
  LOCK_ROW: 'Chat lock',
  DETAILS_ROW: 'Contact details',
  ADMIN_ROW: 'Open admin console',
  ON: 'On',
  OFF: 'Off',
  NONE: 'None',
  SHARED_TABS: [
    { id: 'media', label: 'Media' },
    { id: 'links', label: 'Links' },
    { id: 'docs', label: 'Docs' }
  ],
  PHOTOS: 'Photos',
  VIDEOS: 'Videos',
  LINKS: 'Links',
  DOCS: 'Docs',
  COUNT_SEPARATOR: ', ',
  MONTH_FORMAT: { month: 'long' },
  YEAR_MONTH_FORMAT: { month: 'long', year: 'numeric' },
  LOCALE: 'en-US',
  SECONDS_PER_MINUTE: 60,
  SECONDS_PAD: 2,
  PAD_CHAR: '0',
  TIME_SEPARATOR: ':',
  EMPTY: { media: 'No photos or videos yet.', links: 'No links yet.', docs: 'No documents or voice messages yet.' },
  EMPTY_VALUE: '—',
  PAGE_TITLES: { starred: 'Starred messages', storage: 'Manage storage', privacy: 'Advanced chat privacy', lock: 'Chat lock', details: 'Contact details', mute: 'Mute notifications', theme: 'Chat theme', clear: 'Clear chat' },
  STAFF_SUBTITLE: 'Support team',
  CUSTOMER_SUBTITLE: 'Customer'
} as const;
