export const INFO_PANEL = {
  TITLE: 'Contact info',
  TITLE_ID: 'info-panel-title',
  STORAGE_ID_PREFIX: 'storage-file-',
  DELETE_NOTE: 'Deleted files disappear for everyone in this chat.',
  OPEN_LABEL: 'Open contact info',
  CLOSE_LABEL: 'Close contact info',
  STORAGE_TITLE: 'Manage storage',
  BACK_LABEL: 'Back to contact info',
  TABS_LABEL: 'Shared in this chat',
  TAB_ITEMS: [
    { id: 'media', label: 'Media' },
    { id: 'docs', label: 'Docs' },
    { id: 'links', label: 'Links' },
    { id: 'starred', label: 'Starred' }
  ],
  ROLE_LABEL: 'Role',
  MEMBER_SINCE_LABEL: 'Member since',
  ACCOUNT_LABEL: 'Account',
  KYC_LABEL: 'Identity check',
  PRIVACY_TITLE: 'Advanced chat privacy',
  PRIVACY_HINT: 'When on, the other person can view media and files in this chat but cannot download them, and chat previews show no message text. Screenshots are still possible.',
  LOCK_TITLE: 'Lock this chat',
  LOCK_HINT: 'Opening a locked chat needs your passkey, and the chat list shows no message text for it. Only you are affected.',
  ADMIN_LINK: 'Open admin console',
  ADMIN_ROUTE: '/admin',
  STORAGE_USED: 'used in this chat',
  CUSTOMER_TOTAL: 'Across all of this customer’s chats',
  YOURS_LABEL: 'Yours',
  THEIRS_LABEL: 'Not yours — only the sender can delete it',
  SELECT_LABEL: 'Select',
  DELETE_SELECTED: 'Delete selected',
  NO_FILES: 'No files in this chat yet.',
  EMPTY: { media: 'No photos or videos yet.', docs: 'No documents or voice messages yet.', links: 'No links yet.', starred: 'Star a message to find it here.' },
  LOAD_MORE: 'Load more',
  OPEN_LINK: 'Open link',
  VOICE_NAME: 'Voice message',
  VIDEO_LABEL: 'Video',
  UNSTAR_LABEL: 'Remove star',
  ATTACHMENT_LABEL: 'Attachment',
  DATE_FORMAT: 'mediumDate',
  THUMB_SIZE: 112
} as const;
