export const SUPPORT_VIEW = {
  FALLBACK_NAME: 'Support',
  FALLBACK_INITIAL: '?',
  UNDERSCORE: '_',
  SPACE: ' ',
  OFFLINE: 'OFFLINE',
  ATTACH_SOON: 'Attachments are coming next',
  ONLINE_LABEL: 'Online',
  CONVERSATIONS_LABEL: 'conversations',
  AVAILABLE_LABEL: 'available',
  CONVERSATION_LABEL: 'conversation',
  AWAY_LABEL: 'Away',
  PICK_HINT: 'Pick a conversation',
  AUTO_OPEN_MS: 400,
  OFFLINE_LABEL: 'Offline',
  JUST_NOW: 'Last seen just now',
  LAST_SEEN_PREFIX: 'Last seen',
  TODAY_AT: 'at ',
  JUST_NOW_MINUTES: 2,
  MINUTES_PER_HOUR: 60,
  MINUTE_MS: 60000,
  SENT_LABEL: 'Sent',
  SEEN_LABEL: 'Seen',
  DELIVERED_LABEL: 'Delivered',
  BACK_LABEL: 'Back to chats',
  MAX_COMPOSER_HEIGHT: 140,
  UNREAD_DIVIDER: 'Unread messages',
  JUMP_LABEL: 'Jump to latest',
  UNSEEN_CAP: 99,
  UNSEEN_OVERFLOW: '99+',
  DROP_HINT: 'Drop files to send',
  TYPING_LABEL: 'typing…',
  MESSAGE_ID_PREFIX: 'message-',
  REPLY_ACTION: 'Reply',
  REPLYING_LABEL: 'Replying to',
  CANCEL_REPLY: 'Cancel reply',
  YOU_LABEL: 'You',
  QUOTE_DELETED: 'Message deleted',
  QUOTE_ATTACHMENT: 'Attachment'
} as const;
