export const CRYPTO_DEFAULTS = {
  CIPHER_ALGORITHM: 'aes-256-gcm',
  CIPHER_IV_BYTES: 12,
  CIPHER_KEY_BYTES: 32,
  CIPHER_TAG_BYTES: 16,
  HASH_ALGORITHM: 'sha256',
  RSA_MODULUS_LENGTH: 2048
} as const;
