export const RECEIPT = {
  BRAND: 'WalletPay',
  PLATFORM_NAME: 'Realtime Wallet Payments',
  LOGO_LETTER: 'W',
  TITLE: 'RECEIPT',
  CONTENT_TYPE: 'application/pdf',
  DISPOSITION_PREFIX: 'attachment; filename="receipt-',
  DISPOSITION_SUFFIX: '.pdf"',
  NUMBER_PREFIX: 'R-',
  NUMBER_LENGTH: 8,
  LOCALE: 'en-GB',
  MONEY_LOCALE: 'en-US',
  TIME_ZONE: 'UTC',
  DATE_STYLE: 'long',
  TIME_STYLE: 'short',
  CURRENCY_STYLE: 'currency',
  DECIMAL_BASE: 10,
  ID_SEPARATOR: /-/g,
  EMPTY: '',
  SPACE: ' ',
  NOT_AVAILABLE: 'A receipt is only available for a completed payment',
  NOT_FOUND: 'Payment not found',
  UNKNOWN_METHOD: 'Not recorded',
  MASK: '•••• ',
  DATA_EVENT: 'data',
  END_EVENT: 'end',
  ERROR_EVENT: 'error',
  TYPE_LABELS: { DEPOSIT: 'Deposit', WITHDRAWAL: 'Withdrawal' } as Record<string, string>,
  AMOUNT_LABELS: { DEPOSIT: 'Amount deposited', WITHDRAWAL: 'Amount withdrawn' } as Record<string, string>,
  DEFAULT_AMOUNT_LABEL: 'Amount',
  LABELS: {
    NUMBER: 'Receipt no.',
    DATE: 'Date',
    TYPE: 'Transaction type',
    METHOD: 'Payment method',
    PAYMENT_ID: 'Payment ID',
    PROVIDER_REFERENCE: 'Provider reference',
    DETAILS: 'PAYMENT DETAILS',
    BILLED_TO: 'BILLED TO',
    PAID_ON: 'Paid on'
  },
  FOOTER: 'This receipt was generated on request and is not stored. Keep it for your records.',
  GENERATED_PREFIX: 'Generated '
} as const;
