export const SUPPORT_ATTACHMENT = {
  FIELD_NAME: 'files',
  EDIT_FIELD_NAME: 'file',
  MAX_FILES: 5,
  SINGLE_FILE: 1,
  MAX_FILE_SIZE_BYTES: 10 * 1024 * 1024,
  KEY_PREFIX: 'support',
  KEY_SEPARATOR: '/',
  URL_TTL_SECONDS: 3600,
  TEXT_SNIFF_BYTES: 4096,
  NUL_BYTE: 0,
  MIME_PARAMS_SEPARATOR: ';',
  RECORDED_KINDS: ['VOICE', 'VIDEO'] as readonly string[],
  MAX_DURATION_SECONDS: 15 * 60,
  NOT_EDITABLE_MESSAGE: 'Voice and video messages cannot be edited',
  FILE_NAME_MAX_LENGTH: 255,
  CONTROL_CHAR_LIMIT: 32,
  UNSAFE_PATH_CHARS: ['/', '\\'] as readonly string[],
  SAFE_REPLACEMENT: '_',
  NO_FILES_MESSAGE: 'Attach at least one file',
  TOO_MANY_FILES_MESSAGE: 'You can send up to 5 files at once',
  INVALID_TYPE_MESSAGE: 'That file type is not allowed. Send images, video, audio, PDF, Word, Excel, text or CSV files.',
  MESSAGE_NOT_FOUND_MESSAGE: 'Message not found',
  NOT_YOUR_MESSAGE: 'You can only edit your own messages',
  NOTHING_TO_EDIT_MESSAGE: 'Change the text or attach a new file'
} as const;
