import type { z } from 'zod';

import { ACTION_EVENTS } from '../constants/messaging/action-events.constant';
import { AGGREGATE_TYPES } from '../constants/database/aggregate-types.constant';
import { BETTING_TYPES } from '../constants/betting/betting-types.constant';
import { CACHE_KEYS } from '../constants/cache/cache-keys.constant';
import { CACHE_TTLS } from '../constants/cache/cache-ttls.constant';
import { DatabaseErrorCodes } from '../constants/database/database-error-codes.constant';
import { HttpStatuses } from '../constants/errors/http-statuses.constant';
import { JOIN_CLAUSE_TYPES } from '../constants/database/join-clause-types.constant';
import { MODULES_KEYS } from '../constants/app/modules-keys.constant';
import { OPERATORS } from '../constants/database/operators.constant';
import { ORDER_DIRECTIONS } from '../constants/database/order-directions.constant';
import { RABBITMQ_KEYS } from '../constants/messaging/rabbitmq-keys.constant';
import { STORAGE_STRATEGIES } from '../constants/storage/storage-strategies.constant';
import { TranslationCodes } from '../constants/database/translation-codes.constant';
import { WALLET_STATUS } from '../constants/wallet/wallet-status.constant';

export type ActionEvent = (typeof ACTION_EVENTS)[number];
export type AggregateFunction = 'SUM' | 'COUNT';
export type AggregateType = (typeof AGGREGATE_TYPES)[number];
export type AsyncMethod = (...args: unknown[]) => Promise<unknown>;
export type BettingType = (typeof BETTING_TYPES)[number];
export type CacheKey = (typeof CACHE_KEYS)[number];
export type CacheTTL = (typeof CACHE_TTLS)[number];
export type DatabaseErrorCode = (typeof DatabaseErrorCodes)[number];
export type EntityData = UnknownRecord;
export type EntityId = string | number;
export type HandleRecord = (payload: UnknownRecord) => Promise<void>;
export type HeadersPayload = Record<string, string | Buffer | (string | Buffer)[]>;
export type HttpStatus = (typeof HttpStatuses)[number];
export type JoinClauseTypes = (typeof JOIN_CLAUSE_TYPES)[number];
export type MessageHandler<T = unknown> = (payload: T) => Promise<void> | void;
export type ModuleRegistry = Record<string, { key: (typeof MODULES_KEYS)[number] }>;
type Operators = (typeof OPERATORS)[number];
export type OrderDirection = (typeof ORDER_DIRECTIONS)[number];
export type PaginationShape = { page: z.ZodDefault<z.ZodCoercedNumber>; limit: z.ZodDefault<z.ZodCoercedNumber> };
export type ProviderHeaders = Record<string, string | string[] | undefined>;
export type RabbitmqRegistry = Record<string, { key: (typeof RABBITMQ_KEYS)[number] }>;
export type ShutdownHook = () => Promise<void> | void;
export type StorageStrategy = (typeof STORAGE_STRATEGIES)[number];
export type StripeLikeError = { type?: string; code?: string; message?: string; rawType?: string };
export type TranslationCode = (typeof TranslationCodes)[number];
export type UnknownRecord = Record<string, unknown>;
export type UserWalletStatus = (typeof WALLET_STATUS)[number];
export type WhereCondition = { readonly field: string; readonly value: unknown; readonly operator?: Operators };
