import type { z } from 'zod';

import { ACTION_EVENTS } from '../constants/action-events.constant';
import { AGGREGATE_TYPES } from '../constants/aggregate-types.constant';
import { AUDIT_ACTIONS } from '../constants/audit-actions.constant';
import { AUDIT_ENTITY_TYPES } from '../constants/audit-entity-types.constant';
import { BETTING_TYPES } from '../constants/betting-types.constant';
import { CACHE_KEYS } from '../constants/cache-keys.constant';
import { CACHE_TTLS } from '../constants/cache-ttls.constant';
import { DatabaseErrorCodes } from '../constants/database-error-codes.constant';
import { FLOW_DIRECTIONS } from '../constants/flow-directions.constant';
import { HttpStatuses } from '../constants/http-statuses.constant';
import { JOIN_CLAUSE_TYPES } from '../constants/join-clause-types.constant';
import { MODULES_KEYS } from '../constants/modules-keys.constant';
import { OPERATORS } from '../constants/operators.constant';
import { ORDER_DIRECTIONS } from '../constants/order-directions.constant';
import { RABBITMQ_KEYS } from '../constants/rabbitmq-keys.constant';
import { STORAGE_STRATEGIES } from '../constants/storage-strategies.constant';
import { TOKEN_TYPES } from '../constants/token-types.constant';
import { TranslationCodes } from '../constants/translation-codes.constant';
import { WALLET_STATUS } from '../constants/wallet-status.constant';
import { WORKFLOW_NAMES } from '../constants/workflow-names.constant';
import { WORKFLOW_STEPS } from '../constants/workflow-steps.constant';
import { WorkflowStepStatus } from '../enums/common/events.enum';

export type ActionEvent = (typeof ACTION_EVENTS)[number];
export type AggregateFunction = 'SUM' | 'COUNT';
export type AggregateType = (typeof AGGREGATE_TYPES)[number];
export type AsyncMethod = (...args: unknown[]) => Promise<unknown>;
export type AuditAction = (typeof AUDIT_ACTIONS)[number];
export type AuditEntityType = (typeof AUDIT_ENTITY_TYPES)[number];
export type BettingType = (typeof BETTING_TYPES)[number];
export type CacheKey = (typeof CACHE_KEYS)[number];
export type CacheTTL = (typeof CACHE_TTLS)[number];
export type DatabaseErrorCode = (typeof DatabaseErrorCodes)[number];
export type EntityData = UnknownRecord;
export type EntityId = string | number;
export type FlowDirection = (typeof FLOW_DIRECTIONS)[number];
export type HandleRecord = (payload: UnknownRecord) => Promise<void>;
export type HeadersPayload = Record<string, string | Buffer | (string | Buffer)[]>;
export type HttpStatus = (typeof HttpStatuses)[number];
export type JoinClauseTypes = (typeof JOIN_CLAUSE_TYPES)[number];
export type MessageHandler<T = unknown> = (payload: T) => Promise<void> | void;
export type ModuleRegistry = Record<string, { key: (typeof MODULES_KEYS)[number] }>;
export type Operators = (typeof OPERATORS)[number];
export type OrderDirection = (typeof ORDER_DIRECTIONS)[number];
export type PaginationShape = { page: z.ZodDefault<z.ZodCoercedNumber>; limit: z.ZodDefault<z.ZodCoercedNumber> };
export type ProviderHeaders = Record<string, string | string[] | undefined>;
export type RabbitmqRegistry = Record<string, { key: (typeof RABBITMQ_KEYS)[number] }>;
export type RemoveUndefined<T> = { [K in keyof T]: Exclude<T[K], undefined> };
export type ShutdownHook = () => Promise<void> | void;
export type StorageStrategy = (typeof STORAGE_STRATEGIES)[number];
export type StripeLikeError = { type?: string; code?: string; message?: string; rawType?: string };
export type TokenType = (typeof TOKEN_TYPES)[number];
export type Topic = string | RegExp;
export type TranslationCode = (typeof TranslationCodes)[number];
export type UnknownRecord = Record<string, unknown>;
export type UserWalletStatus = (typeof WALLET_STATUS)[number];
export type WhereCondition = { readonly field: string; readonly value: unknown; readonly operator?: Operators };
export type WorkflowContext = Record<string, unknown>;
export type WorkflowExecutionRecord = { readonly stepName: string; readonly status: WorkflowStepStatus };
export type WorkflowNames = (typeof WORKFLOW_NAMES)[number];
export type WorkflowSteps = (typeof WORKFLOW_STEPS)[number];
