apiVersion: 1

datasources:
  # Prometheus Data Source
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: '15s'
      httpMethod: POST
    version: 1

  # ClickHouse Data Source
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    editable: true
    jsonData:
      defaultDatabase: analytics
      port: 9000
      protocol: native
      server: clickhouse
      username: default
      tlsSkipVerify: true
    secureJsonData:
      password: clickhouse_pass
    version: 1
