import { METRICS } from './metrics.constant';

export const METRIC_GAUGES = {
  NAMES: [
    METRICS.POOL_TOTAL,
    METRICS.POOL_IDLE,
    METRICS.POOL_WAITING,
    METRICS.OUTBOX_PENDING,
    METRICS.OUTBOX_DEAD,
    METRICS.OUTBOX_LAG,
    METRICS.LEDGER_DRIFTED_ACCOUNTS,
    METRICS.LEDGER_DRIFTED_WALLETS,
    METRICS.LEDGER_UNBALANCED_CURRENCIES
  ]
} as const;
