export const WALLET_STATUSES = ['ACTIVE', 'CLOSED', 'SUSPENDED'] as const;

export const WALLET_TRANSACTION_STATUSES = ['COMPLETED', 'FAILED', 'PENDING', 'REVERSED'] as const;

export const WALLET_TRANSACTION_TYPES = ['ADJUSTMENT', 'BET_PAYOUT', 'BET_REFUND', 'BET_STAKE', 'DEPOSIT', 'FEE', 'WITHDRAWAL'] as const;
