export const AUDIT_ACTIONS = [
  'BET_SETTLED',
  'PAYMENT_METHOD_REMOVED',
  'PAYMENT_METHOD_VERIFIED',
  'USER_ANONYMIZED',
  'USER_CREATED',
  'USER_DELETED',
  'USER_REACTIVATED',
  'USER_ROLE_CHANGED',
  'USER_SUSPENDED',
  'WALLET_CREDITED',
  'WALLET_DEBITED',
  'WALLET_STATUS_CHANGED'
] as const;
