export const USER_AUDIT = {
  ENTITY_TYPE: 'User',
  ENTITY_ID_PARAM: 'userId',
  CREATED: 'USER_CREATED',
  DELETED: 'USER_DELETED',
  ANONYMIZED: 'USER_ANONYMIZED',
  SUSPENDED: 'USER_SUSPENDED',
  REACTIVATED: 'USER_REACTIVATED'
} as const;
