export const LOAD_STATE = {
  DEFAULT_ROWS: 3,
  ERROR_TITLE: 'Something went wrong',
  ERROR_MESSAGE: 'We could not load this. Check your connection and try again.',
  RETRY_LABEL: 'Try again',
  NOTIFICATIONS_EMPTY_TITLE: 'No notifications',
  NOTIFICATIONS_EMPTY_MESSAGE: 'Payments, bets and account updates will show up here.',
  NOTIFICATIONS_ICON: 'bell',
  WALLET_ERROR: 'We could not load your wallet. Try again in a moment.',
  DASHBOARD_ERROR: 'We could not load your balance and recent activity.',
  LEDGER_ERROR: 'We could not load the ledger entries.',
  EVENTS_ERROR: 'We could not load the events.',
  METHODS_ERROR: 'We could not load your payment methods.',
  MFA_ERROR: 'We could not load your two-factor status.',
  ADMIN_ERROR: 'We could not load the users and stats.',
  EVENTS_EMPTY_TITLE: 'No events open right now',
  EVENTS_EMPTY_MESSAGE: 'New fixtures appear here as soon as betting opens.',
  EVENTS_ICON: 'trophy',
  BETS_EMPTY_TITLE: 'No bets yet',
  BETS_EMPTY_MESSAGE: 'Place your first bet on an available event',
  BETS_ICON: 'target',
  EVENT_ROWS: 2,
  SECTION_ROWS: 1
} as const;
