export const SUPPORT = {
  BASE_PATH: '/support',
  ROUTE: '/support',
  CONVERSATIONS_PATH: '/conversations',
  MESSAGES_PATH: '/messages',
  READ_PATH: '/read',
  PRESENCE_PATH: '/presence',
  PRESENCE_COUNT_PATH: '/presence/count',
  PRESENCE_PAGE_SIZE: 100,
  HEARTBEAT_PATH: '/presence/heartbeat',
  LEAVE_PATH: '/presence/leave',
  LAST_SEEN_PATH: '/presence/last-seen',
  CONTACTS_PATH: '/contacts',
  ONLINE_STATE: 'ONLINE',
  OFFLINE_STATE: 'OFFLINE',
  TICKET_PATH: '/stream-ticket',
  STREAM_PATH: '/stream',
  TICKET_PARAM: 'ticket',
  HEARTBEAT_MS: 20000,
  PRESENCE_RESYNC_MS: 120000,
  RECONNECT_BASE_MS: 1000,
  RECONNECT_MAX_MS: 30000,
  BODY_MAX_LENGTH: 4000,
  PAGE_SIZE: 50
} as const;
