export const SUPPORT_PANEL = {
  LINK_PATTERN: /https?:\/\//i,
  SIGNATURE_JOIN: ':',
  SIGNATURE_SEPARATOR: '|',
  REFRESH_DEBOUNCE_MS: 400,
  CONTACT_PATH: '/contact',
  STORAGE_PATH: '/storage',
  STARRED_PATH: '/starred',
  STAR_PATH: '/star',
  PRIVACY_PATH: '/privacy',
  DOWNLOAD_PATH: '/download',
  LOCK_PATH: '/lock',
  CHAT_LOCK_PATH: '/chat-lock',
  CHAT_UNLOCK_PATH: '/chat-unlock',
  LOCK_FAILED: 'Could not lock this chat. Add a passkey on your profile first.',
  UNLOCK_FAILED: 'This chat stays locked until you confirm with your passkey.',
  LOCKED: 'Chat locked. It now needs your passkey to open.',
  UNLOCKED: 'Chat lock removed.',
  CONVERSATION_UPDATED_EVENT: 'support.conversation.updated',
  PRIVACY_FAILED: 'Could not change chat privacy. Try again.',
  DOWNLOAD_FAILED: 'This file cannot be downloaded.',
  LIMIT_PARAM: 'limit',
  BEFORE_PARAM: 'before',
  BEFORE_ID_PARAM: 'beforeId',
  PAGE_SIZE: 30,
  TABS: { MEDIA: 'media', DOCS: 'docs', LINKS: 'links', STARRED: 'starred' },
  PAGED_TABS: ['media', 'docs', 'links'],
  DESKTOP_QUERY: '(min-width: 768px)',
  LOAD_FAILED: 'Could not load this section. Try again.',
  STAR_FAILED: 'Could not update the star. Try again.',
  DELETE_FAILED: 'Could not delete the files. Try again.',
  DELETED_ONE: 'File deleted',
  DELETED_MANY: 'files deleted'
} as const;
