export const SUPPORT_RECORDING = {
  VOICE: 'voice',
  VIDEO: 'video',
  VOICE_MAX_MS: 15 * 60 * 1000,
  VIDEO_MAX_MS: 60 * 1000,
  TIMESLICE_MS: 250,
  INACTIVE_STATE: 'inactive',
  TICK_MS: 500,
  PREVIEW_FRACTION: 0.5,
  WARMUP_MS: 900,
  MS_PER_SECOND: 1000,
  AUDIO_BITS: 32000,
  VIDEO_BITS: 800000,
  VIDEO_SIZE: 480,
  FACING_MODE: 'user',
  VOICE_TYPES: ['audio/webm;codecs=opus', 'audio/ogg;codecs=opus', 'audio/mp4'] as readonly string[],
  VIDEO_TYPES: ['video/webm;codecs=vp8,opus', 'video/webm', 'video/mp4'] as readonly string[],
  MIME_PARAMS_SEPARATOR: ';',
  TYPE_SEPARATOR: '/',
  VOICE_FILE_PREFIX: 'voice-message',
  VIDEO_FILE_PREFIX: 'video-message',
  EXTENSION_SEPARATOR: '.',
  RECORD_VOICE: 'Record a voice message',
  RECORD_VIDEO: 'Record a video message',
  CANCEL_RECORDING: 'Cancel recording',
  SEND_RECORDING: 'Send recording',
  RECORDING_LABEL: 'Recording',
  NOT_SUPPORTED: 'Recording is not supported in this browser.',
  DENIED: 'Allow microphone and camera access to record messages.',
  PLAY: 'Play',
  PAUSE: 'Pause'
} as const;
