export const SUPPORT_CALL = {
  CALLS_PATH: '/calls',
  CONFIG_PATH: '/calls/config',
  ANSWER_PATH: '/answer',
  CANDIDATES_PATH: '/candidates',
  END_PATH: '/end',
  INCOMING_EVENT: 'support.call.incoming',
  ANSWERED_EVENT: 'support.call.answered',
  CANDIDATE_EVENT: 'support.call.candidate',
  ENDED_EVENT: 'support.call.ended',
  AUDIO: 'AUDIO',
  VIDEO: 'VIDEO',
  HANGUP: 'HANGUP',
  DECLINED: 'DECLINED',
  MISSED: 'MISSED',
  BUSY: 'BUSY',
  FAILED: 'FAILED',
  VIDEO_TRACK: 'video',
  SCREEN_HINT: 'detail',
  CAMERA_HINT: 'motion',
  SCREEN_DEGRADATION: 'maintain-resolution',
  CAMERA_DEGRADATION: 'balanced',
  SCREEN_MAX_BITRATE: 2_500_000,
  SCREEN_FRAME_RATE: 15,
  EXCLUDE: 'exclude',
  INCLUDE: 'include',
  SEND_RECEIVE: 'sendrecv',
  SDP_OFFER: 'offer',
  SDP_ANSWER: 'answer',
  CONNECTED_STATE: 'connected',
  FAILED_STATE: 'failed',
  PERMISSION_ERROR: 'NotAllowedError',
  CONFLICT_STATUS: 409,
  RING_TIMEOUT_MS: 45000,
  END_DELAY_MS: 2000,
  TICK_MS: 1000,
  SECONDS_PER_MINUTE: 60,
  MS_PER_SECOND: 1000,
  PAD_LENGTH: 2,
  PAD_CHAR: '0',
  TIME_SEPARATOR: ':',
  CALLING: 'Calling…',
  INCOMING_VOICE: 'Incoming voice call',
  INCOMING_VIDEO: 'Incoming video call',
  CONNECTING: 'Connecting…',
  CALL_ENDED: 'Call ended',
  DECLINED_NOTICE: 'Call declined',
  NO_ANSWER: 'No answer',
  BUSY_NOTICE: 'On another call',
  MISSED_NOTICE: 'Missed call',
  FAILED_NOTICE: 'Call failed',
  MIC_DENIED: 'Allow microphone and camera access to make calls',
  ACCEPT: 'Accept',
  DECLINE: 'Decline',
  HANG_UP: 'Hang up',
  MUTE: 'Mute',
  UNMUTE: 'Unmute',
  CAMERA_OFF: 'Turn camera off',
  CAMERA_ON: 'Turn camera on',
  SHARE_SCREEN: 'Present your screen',
  STOP_SHARING: 'Stop presenting',
  SHARING_NOTICE: 'You are presenting',
  SHARING_HINT: 'Everyone in the call can see your screen.',
  VOICE_CALL: 'Voice call',
  VIDEO_CALL: 'Video call'
} as const;
