export const SUPPORT_ATTACHMENT = {
  FIELD_NAME: 'files',
  EDIT_FIELD_NAME: 'file',
  BODY_FIELD: 'body',
  ATTACHMENTS_PATH: '/attachments',
  MAX_FILES: 5,
  MAX_FILE_SIZE_BYTES: 10 * 1024 * 1024,
  ACCEPT: 'image/jpeg,image/png,image/gif,image/webp,application/pdf,text/plain,text/csv,application/msword,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,video/mp4,video/webm,audio/webm,audio/ogg,audio/mp4',
  MIME_PARAMS_SEPARATOR: ';',
  DURATION_FIELD: 'durationSeconds',
  VOICE_KIND: 'VOICE',
  VIDEO_KIND: 'VIDEO',
  ACCEPT_SEPARATOR: ',',
  IMAGE_KIND: 'IMAGE',
  MESSAGE_UPDATED_EVENT: 'support.message.updated',
  BYTES_PER_KB: 1024,
  SIZE_UNITS: ['B', 'KB', 'MB'] as readonly string[],
  SIZE_DECIMALS: 1,
  TOO_MANY_FILES: 'You can send up to 5 files at once.',
  TOO_LARGE: 'Each file must be 10 MB or smaller.',
  WRONG_TYPE: 'Send images, video, audio, PDF, Word, Excel, text or CSV files.',
  EDIT_FAILED: 'Could not save your changes.',
  EDITING_LABEL: 'Editing message',
  EDITED_LABEL: 'edited',
  EDIT_ACTION: 'Edit message',
  CANCEL_EDIT: 'Cancel editing',
  REMOVE_FILE: 'Remove file',
  ATTACH_LABEL: 'Attach files',
  REPLACE_LABEL: 'Replace the file',
  OPEN_FILE: 'Open file'
} as const;
