export const PARAMETERS_CONSTANTS = {
  LOGGER_CONTEXT: 'ParametersLoader',
  LABEL: 'parameters',
  KEYS: {
    SOURCE: 'PARAMETERS_SOURCE',
    REGION: 'PARAMETERS_REGION',
    ENDPOINT: 'PARAMETERS_ENDPOINT',
    ACCESS_KEY_ID: 'PARAMETERS_ACCESS_KEY_ID',
    SECRET_ACCESS_KEY: 'PARAMETERS_SECRET_ACCESS_KEY'
  },
  PATH_KEY: 'PARAMETERS_PATH',
  PATH_SEPARATOR: '/',
  PAGE_SIZE: 10,
  ERRORS: {
    MISSING_PATH: 'PARAMETERS_SOURCE is aws but PARAMETERS_PATH is not set'
  }
} as const;
