export enum ProviderErrorCategory {
  AUTHENTICATION = 'AUTHENTICATION',
  CIRCUIT_OPEN = 'CIRCUIT_OPEN',
  DECLINED = 'DECLINED',
  INVALID_REQUEST = 'INVALID_REQUEST',
  NETWORK = 'NETWORK',
  PROVIDER_DOWN = 'PROVIDER_DOWN',
  RATE_LIMIT = 'RATE_LIMIT',
  UNKNOWN = 'UNKNOWN'
}
