export const OUTBOX_SETTINGS_TEST = {
  BATCH_KEY: 'OUTBOX_BATCH_SIZE',
  INTERVAL_KEY: 'OUTBOX_POLL_INTERVAL_MS',
  DEFAULT_BATCH: 50,
  DEFAULT_INTERVAL: 5000,
  CUSTOM_BATCH: '200',
  CUSTOM_BATCH_VALUE: 200,
  CUSTOM_INTERVAL: 1000,
  INVALID: 'fast',
  NEGATIVE: '-5',
  SMALL_BATCH: 10,
  FULL_BATCHES: 2,
  LAST_BATCH: 3
} as const;
